language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - phpenv config-add travis.php.ini
  - mysql -e 'CREATE DATABASE testing;'

install: travis_wait composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

notifications:
  email:
    on_success: never
